//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessmentScore
    {
        public int AssessmentScoreId { get; set; }
        public int AssessmentId { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<decimal> NationalPercentile { get; set; }
        public Nullable<decimal> DistrictPercentile { get; set; }
        public Nullable<int> Projection { get; set; }
        public Nullable<int> GrowthCalc { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
        public Nullable<decimal> ScaledScoreCalc { get; set; }
        public Nullable<int> GradeLevel { get; set; }
        public int SchoolID { get; set; }
        public Nullable<decimal> ScaledProjCalc { get; set; }
        public Nullable<decimal> ScaledScoreProjDif { get; set; }
        public Nullable<int> ScoreProjDif { get; set; }
        public Nullable<decimal> ScaledGrowthCalc { get; set; }
    
        public virtual tblStudent tblStudent { get; set; }
        public virtual tblAssessment tblAssessment { get; set; }
    }
}
