//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttachment
    {
        public tblAttachment()
        {
            this.tblKnowledgeBaseAttachments = new HashSet<tblKnowledgeBaseAttachment>();
        }
    
        public int AttachmentId { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public int CreatedUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string OriginalFileName { get; set; }
    
        public virtual ICollection<tblKnowledgeBaseAttachment> tblKnowledgeBaseAttachments { get; set; }
    }
}
