//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessmentGradeWeighting
    {
        public tblAssessmentGradeWeighting()
        {
            this.tblAssessmentGradeWeightingCategories = new HashSet<tblAssessmentGradeWeightingCategory>();
        }
    
        public int AssessmentGradeWeightingId { get; set; }
        public int AssessmentWeightingId { get; set; }
        public short Grade { get; set; }
        public decimal Weighting { get; set; }
    
        public virtual tblAssessmentWeighting tblAssessmentWeighting { get; set; }
        public virtual ICollection<tblAssessmentGradeWeightingCategory> tblAssessmentGradeWeightingCategories { get; set; }
    }
}
