//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessment
    {
        public tblAssessment()
        {
            this.tblAssessmentExpectations = new HashSet<tblAssessmentExpectation>();
            this.tblAssessmentScores = new HashSet<tblAssessmentScore>();
        }
    
        public int AssessmentId { get; set; }
        public string AssessmentDesc { get; set; }
        public string AssessmentSubDesc { get; set; }
        public int AssessmentTypeId { get; set; }
        public int SchoolYearId { get; set; }
        public int SchoolTermId { get; set; }
        public int SubjectId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
        public Nullable<int> ScoreMin { get; set; }
        public Nullable<int> ScoreMax { get; set; }
        public Nullable<int> SLOTemplateId { get; set; }
        public Nullable<int> RubricTemplateId { get; set; }
    
        public virtual tblAssessmentType tblAssessmentType { get; set; }
        public virtual tblSchoolTerm tblSchoolTerm { get; set; }
        public virtual tblSchoolYear tblSchoolYear { get; set; }
        public virtual tblSubject tblSubject { get; set; }
        public virtual ICollection<tblAssessmentExpectation> tblAssessmentExpectations { get; set; }
        public virtual ICollection<tblAssessmentScore> tblAssessmentScores { get; set; }
        public virtual tblAssessmentTemplate tblAssessmentTemplate { get; set; }
        public virtual tblAssessmentTemplate tblAssessmentTemplate1 { get; set; }
    }
}
