//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessmentTemplate
    {
        public tblAssessmentTemplate()
        {
            this.tblAssessments = new HashSet<tblAssessment>();
            this.tblAssessments1 = new HashSet<tblAssessment>();
        }
    
        public int AssessmentTemplateId { get; set; }
        public string TemplateType { get; set; }
        public string TemplateFileName { get; set; }
    
        public virtual ICollection<tblAssessment> tblAssessments { get; set; }
        public virtual ICollection<tblAssessment> tblAssessments1 { get; set; }
    }
}
