//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessmentGradeWeightingCategory
    {
        public int AssessmentGradeWeightingCategoryId { get; set; }
        public Nullable<int> AssessmentGradeWeightingId { get; set; }
        public decimal Min { get; set; }
        public decimal Max { get; set; }
        public int CategoryId { get; set; }
        public Nullable<decimal> Points { get; set; }
    
        public virtual tblAssessmentGradeWeighting tblAssessmentGradeWeighting { get; set; }
        public virtual tblWeightingCategory tblWeightingCategory { get; set; }
    }
}
