//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessmentExpectation
    {
        public int AssessmentExpectationId { get; set; }
        public int AssessmentId { get; set; }
        public decimal Expectation { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public short GradeLevel { get; set; }
    
        public virtual tblAssessment tblAssessment { get; set; }
    }
}
