//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessmentType
    {
        public tblAssessmentType()
        {
            this.tblAssessmentWeightings = new HashSet<tblAssessmentWeighting>();
            this.tblAssessmentType1 = new HashSet<tblAssessmentType>();
            this.tblAssessments = new HashSet<tblAssessment>();
        }
    
        public int AssessmentTypeId { get; set; }
        public string AssessmentCode { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
        public int ReportTemplateId { get; set; }
        public string AssessmentTypeDesc { get; set; }
        public Nullable<int> ParentAssessmentTypeId { get; set; }
    
        public virtual tblReportTemplate tblReportTemplate { get; set; }
        public virtual ICollection<tblAssessmentWeighting> tblAssessmentWeightings { get; set; }
        public virtual ICollection<tblAssessmentType> tblAssessmentType1 { get; set; }
        public virtual tblAssessmentType tblAssessmentType2 { get; set; }
        public virtual ICollection<tblAssessment> tblAssessments { get; set; }
    }
}
