//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClass
    {
        public tblClass()
        {
            this.tblClassStudents = new HashSet<tblClassStudent>();
            this.tblClassTeachers = new HashSet<tblClassTeacher>();
        }
    
        public int ClassId { get; set; }
        public int SchoolId { get; set; }
        public string ClassDesc { get; set; }
        public int SchoolYearId { get; set; }
        public int SubjectId { get; set; }
        public short Grade { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
    
        public virtual tblSchool tblSchool { get; set; }
        public virtual tblSchoolYear tblSchoolYear { get; set; }
        public virtual tblSubject tblSubject { get; set; }
        public virtual ICollection<tblClassStudent> tblClassStudents { get; set; }
        public virtual ICollection<tblClassTeacher> tblClassTeachers { get; set; }
    }
}
