//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDistrict
    {
        public tblDistrict()
        {
            this.tblAssessmentWeightings = new HashSet<tblAssessmentWeighting>();
            this.tblSchools = new HashSet<tblSchool>();
            this.tblStudents = new HashSet<tblStudent>();
            this.tblAnnouncements = new HashSet<tblAnnouncement>();
            this.tblKnowledgeBases = new HashSet<tblKnowledgeBase>();
            this.tblUserDistricts = new HashSet<tblUserDistrict>();
        }
    
        public int DistrictId { get; set; }
        public string DistrictDesc { get; set; }
        public Nullable<System.DateTime> ServiceEndDatetime { get; set; }
        public Nullable<short> LicensesPurchased { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
    
        public virtual ICollection<tblAssessmentWeighting> tblAssessmentWeightings { get; set; }
        public virtual ICollection<tblSchool> tblSchools { get; set; }
        public virtual ICollection<tblStudent> tblStudents { get; set; }
        public virtual ICollection<tblAnnouncement> tblAnnouncements { get; set; }
        public virtual ICollection<tblKnowledgeBase> tblKnowledgeBases { get; set; }
        public virtual ICollection<tblUserDistrict> tblUserDistricts { get; set; }
    }
}
