//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnrollmentType
    {
        public tblEnrollmentType()
        {
            this.tblStudents = new HashSet<tblStudent>();
            this.tblStudentSchoolYears = new HashSet<tblStudentSchoolYear>();
        }
    
        public int EnrollmentTypeId { get; set; }
        public string EnrollmentTypeCode { get; set; }
        public string EnrollmentTypeDesc { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
    
        public virtual ICollection<tblStudent> tblStudents { get; set; }
        public virtual ICollection<tblStudentSchoolYear> tblStudentSchoolYears { get; set; }
    }
}
