//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImportStudent
    {
        public int ImportStudentId { get; set; }
        public int ImportId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string StateId { get; set; }
        public string LocalId { get; set; }
        public string LineageCode { get; set; }
        public string RaceCode { get; set; }
        public string GenderCode { get; set; }
        public string BirthDate { get; set; }
        public string HomeLanguageCode { get; set; }
        public string NativeLanguageCode { get; set; }
        public string LepIndicatorCode { get; set; }
        public string IepIndicatorCode { get; set; }
        public string FrlLiCode { get; set; }
        public string EnrollmentType { get; set; }
        public string EnrollmentDate { get; set; }
        public string RcdtsCode_HomeSchool { get; set; }
        public string RcdtsCode_ServingSchool { get; set; }
        public string GradeLevel { get; set; }
        public string SchoolYear { get; set; }
    
        public virtual tblImport tblImport { get; set; }
    }
}
