//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImport
    {
        public tblImport()
        {
            this.tblImportAttributes = new HashSet<tblImportAttribute>();
            this.tblImportIsats = new HashSet<tblImportIsat>();
            this.tblImportMaps = new HashSet<tblImportMap>();
            this.tblImportStudents = new HashSet<tblImportStudent>();
            this.tblImportUsers = new HashSet<tblImportUser>();
        }
    
        public int ImportId { get; set; }
        public int ImportTypeId { get; set; }
        public string ImportFile { get; set; }
        public int UserId { get; set; }
        public bool ReadyToProcess { get; set; }
        public Nullable<System.DateTime> ProcesseDateTime { get; set; }
        public System.DateTime CreateDatetime { get; set; }
    
        public virtual tblImportType tblImportType { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<tblImportAttribute> tblImportAttributes { get; set; }
        public virtual ICollection<tblImportIsat> tblImportIsats { get; set; }
        public virtual ICollection<tblImportMap> tblImportMaps { get; set; }
        public virtual ICollection<tblImportStudent> tblImportStudents { get; set; }
        public virtual ICollection<tblImportUser> tblImportUsers { get; set; }
    }
}
