//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImportMap
    {
        public int ImportMapId { get; set; }
        public int ImportId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleInitial { get; set; }
        public string LocalId { get; set; }
        public string TestDate { get; set; }
        public string RIT_ { get; set; }
        public string RIT { get; set; }
        public string RIT_1 { get; set; }
        public string Perc_ { get; set; }
        public string Perc { get; set; }
        public string Perc_1 { get; set; }
        public string LexileRange { get; set; }
        public string TestDuration { get; set; }
        public string Goal_Score_1 { get; set; }
        public string Goal_Score_2 { get; set; }
        public string Goal_Score_3 { get; set; }
        public string Goal_Score_4 { get; set; }
        public string Goal_Score_5 { get; set; }
    
        public virtual tblImport tblImport { get; set; }
    }
}
