//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImportUser
    {
        public int ImportUserId { get; set; }
        public int ImportId { get; set; }
        public string UserEmail { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StateId { get; set; }
        public string LocalId { get; set; }
        public string SchoolAbbr_CheckLocationCode { get; set; }
        public string SchoolAbbr_BuildingCode1 { get; set; }
        public string SchoolAbbr_BuildingCode2 { get; set; }
        public string SchoolAbbr_BuildingCode3 { get; set; }
        public string SchoolAbbr_BuildingCode4 { get; set; }
        public string SchoolAbbr_BuildingCode5 { get; set; }
        public string AssignmentDescription1 { get; set; }
        public string AssignmentDescription2 { get; set; }
        public string AssignmentDescription3 { get; set; }
        public string AssignmentDescription4 { get; set; }
        public string AssignmentDescription5 { get; set; }
        public string Fte1 { get; set; }
        public string Fte2 { get; set; }
        public string Fte3 { get; set; }
        public string Fte4 { get; set; }
        public string Fte5 { get; set; }
    
        public virtual tblImport tblImport { get; set; }
    }
}
