//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImportAttribute
    {
        public int ImportAttributesId { get; set; }
        public int ImportId { get; set; }
        public int ImportTypeAttributeId { get; set; }
        public string AttributeValue { get; set; }
    
        public virtual tblImport tblImport { get; set; }
        public virtual tblImportTypeAttribute tblImportTypeAttribute { get; set; }
    }
}
