//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImportTypeAttribute
    {
        public tblImportTypeAttribute()
        {
            this.tblImportAttributes = new HashSet<tblImportAttribute>();
        }
    
        public int ImportTypeAttibuteId { get; set; }
        public int ImportTypeId { get; set; }
        public string ImportAttribute { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
    
        public virtual ICollection<tblImportAttribute> tblImportAttributes { get; set; }
        public virtual tblImportType tblImportType { get; set; }
    }
}
