//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImportType
    {
        public tblImportType()
        {
            this.tblImports = new HashSet<tblImport>();
            this.tblImportTypeAttributes = new HashSet<tblImportTypeAttribute>();
        }
    
        public int ImportTypeId { get; set; }
        public string ImportTypeDesc { get; set; }
        public bool ImportEnabled { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
    
        public virtual ICollection<tblImport> tblImports { get; set; }
        public virtual ICollection<tblImportTypeAttribute> tblImportTypeAttributes { get; set; }
    }
}
