//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLineage
    {
        public tblLineage()
        {
            this.tblStudents = new HashSet<tblStudent>();
        }
    
        public int LineageId { get; set; }
        public string LineageCode { get; set; }
        public string LineageDesc { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
    
        public virtual ICollection<tblStudent> tblStudents { get; set; }
    }
}
