//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReportTemplateConfiguration
    {
        public int ConfigId { get; set; }
        public int TemplateId { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    
        public virtual tblReportTemplate tblReportTemplate { get; set; }
    }
}
