//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReportTemplate
    {
        public tblReportTemplate()
        {
            this.tblReportTemplateConfigurations = new HashSet<tblReportTemplateConfiguration>();
            this.tblAssessmentTypes = new HashSet<tblAssessmentType>();
        }
    
        public int TemplateId { get; set; }
        public string TemplateName { get; set; }
    
        public virtual ICollection<tblReportTemplateConfiguration> tblReportTemplateConfigurations { get; set; }
        public virtual ICollection<tblAssessmentType> tblAssessmentTypes { get; set; }
    }
}
