//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRole
    {
        public tblRole()
        {
            this.tblUsers = new HashSet<tblUser>();
            this.tblAnnouncements = new HashSet<tblAnnouncement>();
            this.tblKnowledgeBases = new HashSet<tblKnowledgeBase>();
            this.tblUserDistricts = new HashSet<tblUserDistrict>();
        }
    
        public int RoleId { get; set; }
        public string RoleDesc { get; set; }
        public bool AllowImportUser { get; set; }
        public bool AllowImportStudent { get; set; }
        public bool AllowImportScore { get; set; }
        public bool AllowMaintainUser { get; set; }
        public bool AllowMaintainStudent { get; set; }
        public bool AllowMaintainScore { get; set; }
        public bool AllowMaintanDistrict { get; set; }
        public bool AllowMaintanSchool { get; set; }
        public bool AllowMaintanClass { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
    
        public virtual ICollection<tblUser> tblUsers { get; set; }
        public virtual ICollection<tblAnnouncement> tblAnnouncements { get; set; }
        public virtual ICollection<tblKnowledgeBase> tblKnowledgeBases { get; set; }
        public virtual ICollection<tblUserDistrict> tblUserDistricts { get; set; }
    }
}
