//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRcdt
    {
        public tblRcdt()
        {
            this.tblStudents = new HashSet<tblStudent>();
            this.tblStudents1 = new HashSet<tblStudent>();
        }
    
        public int RcdtsId { get; set; }
        public string RcdtsCode { get; set; }
        public string RcdtsDesc { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
    
        public virtual ICollection<tblStudent> tblStudents { get; set; }
        public virtual ICollection<tblStudent> tblStudents1 { get; set; }
    }
}
