//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubject
    {
        public tblSubject()
        {
            this.tblAssessmentWeightings = new HashSet<tblAssessmentWeighting>();
            this.tblClasses = new HashSet<tblClass>();
            this.tblSchoolYearSubjects = new HashSet<tblSchoolYearSubject>();
            this.tblAssessments = new HashSet<tblAssessment>();
        }
    
        public int SubjectId { get; set; }
        public string SubjectDesc { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
    
        public virtual ICollection<tblAssessmentWeighting> tblAssessmentWeightings { get; set; }
        public virtual ICollection<tblClass> tblClasses { get; set; }
        public virtual ICollection<tblSchoolYearSubject> tblSchoolYearSubjects { get; set; }
        public virtual ICollection<tblAssessment> tblAssessments { get; set; }
    }
}
