//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public tblStudent()
        {
            this.tblAssessmentScores = new HashSet<tblAssessmentScore>();
            this.tblClassStudents = new HashSet<tblClassStudent>();
            this.tblStudentSchoolYears = new HashSet<tblStudentSchoolYear>();
        }
    
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string StateId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string LocalId { get; set; }
        public Nullable<int> LineageId { get; set; }
        public Nullable<int> RaceId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> HomeLanguageId { get; set; }
        public Nullable<int> NativeLanguageId { get; set; }
        public Nullable<bool> LepIndicator { get; set; }
        public Nullable<bool> IepIndicator { get; set; }
        public Nullable<bool> FrlLiIndicator { get; set; }
        public Nullable<int> EnrollmentTypeId { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public Nullable<int> RcdtsId_HomeSchool { get; set; }
        public Nullable<int> RcdtsId_ServingSchool { get; set; }
        public Nullable<short> GradeLevel { get; set; }
        public Nullable<int> SchoolYearId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
    
        public virtual ICollection<tblAssessmentScore> tblAssessmentScores { get; set; }
        public virtual ICollection<tblClassStudent> tblClassStudents { get; set; }
        public virtual tblDistrict tblDistrict { get; set; }
        public virtual tblEnrollmentType tblEnrollmentType { get; set; }
        public virtual tblGender tblGender { get; set; }
        public virtual tblLanguage tblLanguage { get; set; }
        public virtual tblLanguage tblLanguage1 { get; set; }
        public virtual tblLineage tblLineage { get; set; }
        public virtual tblRace tblRace { get; set; }
        public virtual tblRcdt tblRcdt { get; set; }
        public virtual tblRcdt tblRcdt1 { get; set; }
        public virtual tblSchoolYear tblSchoolYear { get; set; }
        public virtual ICollection<tblStudentSchoolYear> tblStudentSchoolYears { get; set; }
    }
}
