//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchoolYear
    {
        public tblSchoolYear()
        {
            this.tblAssessmentWeightings = new HashSet<tblAssessmentWeighting>();
            this.tblClasses = new HashSet<tblClass>();
            this.tblSchoolYearSubjects = new HashSet<tblSchoolYearSubject>();
            this.tblStudents = new HashSet<tblStudent>();
            this.tblStudentSchoolYears = new HashSet<tblStudentSchoolYear>();
            this.tblUserDistricts = new HashSet<tblUserDistrict>();
            this.tblUserSchools = new HashSet<tblUserSchool>();
            this.tblAssessments = new HashSet<tblAssessment>();
        }
    
        public int SchoolYearId { get; set; }
        public int SchoolYear { get; set; }
        public string SchoolYearDesc { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
        public bool IsCurrent { get; set; }
    
        public virtual ICollection<tblAssessmentWeighting> tblAssessmentWeightings { get; set; }
        public virtual ICollection<tblClass> tblClasses { get; set; }
        public virtual ICollection<tblSchoolYearSubject> tblSchoolYearSubjects { get; set; }
        public virtual ICollection<tblStudent> tblStudents { get; set; }
        public virtual ICollection<tblStudentSchoolYear> tblStudentSchoolYears { get; set; }
        public virtual ICollection<tblUserDistrict> tblUserDistricts { get; set; }
        public virtual ICollection<tblUserSchool> tblUserSchools { get; set; }
        public virtual ICollection<tblAssessment> tblAssessments { get; set; }
    }
}
