//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentSchoolYear
    {
        public int StudentSchoolYearId { get; set; }
        public int StudentId { get; set; }
        public int SchoolYearId { get; set; }
        public int ServingSchoolId { get; set; }
        public Nullable<short> GradeLevel { get; set; }
        public string StateId { get; set; }
        public string LocalId { get; set; }
        public bool LepIndicator { get; set; }
        public bool IepIndicator { get; set; }
        public bool FrlIndicator { get; set; }
        public Nullable<int> EnrollmentTypeId { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> ChangeDateTIme { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<int> ChangeUser { get; set; }
        public bool Hispanic { get; set; }
    
        public virtual tblEnrollmentType tblEnrollmentType { get; set; }
        public virtual tblSchool tblSchool { get; set; }
        public virtual tblSchoolYear tblSchoolYear { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
