//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchoolYearSubject
    {
        public int SchoolYearSubjectId { get; set; }
        public int SchoolYearId { get; set; }
        public int SubjectId { get; set; }
        public Nullable<int> FallSpringGrowthTarget { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
    
        public virtual tblSchoolYear tblSchoolYear { get; set; }
        public virtual tblSubject tblSubject { get; set; }
    }
}
