//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserSchool
    {
        public int UserSchoolId { get; set; }
        public int SchoolId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<System.DateTime> ChangedDatetime { get; set; }
        public int SchoolYearId { get; set; }
    
        public virtual tblSchool tblSchool { get; set; }
        public virtual tblSchoolYear tblSchoolYear { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
