//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblClassTeachers = new HashSet<tblClassTeacher>();
            this.tblImports = new HashSet<tblImport>();
            this.tblUserDistricts = new HashSet<tblUserDistrict>();
            this.tblUserSchools = new HashSet<tblUserSchool>();
        }
    
        public int UserId { get; set; }
        public string UserEmail { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StateId { get; set; }
        public string LocalId { get; set; }
        public string AspNetUserId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<System.DateTime> ChangeDatetime { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ICollection<tblClassTeacher> tblClassTeachers { get; set; }
        public virtual ICollection<tblImport> tblImports { get; set; }
        public virtual tblRole tblRole { get; set; }
        public virtual ICollection<tblUserDistrict> tblUserDistricts { get; set; }
        public virtual ICollection<tblUserSchool> tblUserSchools { get; set; }
    }
}
