//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeightingCategory
    {
        public tblWeightingCategory()
        {
            this.tblAssessmentGradeWeightingCategories = new HashSet<tblAssessmentGradeWeightingCategory>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryDesc { get; set; }
    
        public virtual ICollection<tblAssessmentGradeWeightingCategory> tblAssessmentGradeWeightingCategories { get; set; }
    }
}
