//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewMAP
    {
        public int Expr1 { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Score { get; set; }
        public Nullable<int> Projection { get; set; }
        public Nullable<decimal> DistrictPercentile { get; set; }
        public string SchoolYearDesc { get; set; }
        public int SchoolYear { get; set; }
        public string AssessmentDesc { get; set; }
    }
}
